```{r}
library(evir) 
library(evd) 
library(psych) 
library(ismev) 
library(POT) 
library(dplyr)
```

```{r}
data = read.csv("D:/UNI/SKRIPSI/Dataset/20251120_070456.csv")
dataa = data[, -c(1, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 16, 18, 19, 21, 22, 23, 24, 25, 26, 27, 28)]

dataa$waktu_menit <- format(
  as.POSIXct(data$Tanggal...Waktu.Kejadian),
  "%Y-%m-%d %H:%M"
)
dataa <- dataa %>%
  mutate(waktu_menit = format(as.POSIXct(Tanggal...Waktu.Kejadian), "%Y-%m-%d %H:%M")) %>%
  group_by(waktu_menit) %>%
  summarise(
    Meninggal = sum(Meninggal, na.rm = TRUE),
    Luka...Sakit = sum(Luka...Sakit, na.rm = TRUE),
    Rumah.Rusak.Berat = sum(Rumah.Rusak.Berat, na.rm = TRUE)
  )

dataa = dataa[dataa$Meninggal >= 1,]

dataa$casualty = dataa$Meninggal + dataa$Luka...Sakit
dataa$property = dataa$Rumah.Rusak.Berat
```

```{r}
deskripsi = describe(dataa[, c("casualty", "property")])
summary(dataa[, c("casualty", "property")])

par(mfrow = c(1,2))
qqnorm(
  dataa$casualty,
  ylim = c(0, 1500),
  xlim = c(0, 8),
  col = "blue",
  main = "QQ Plot - casualty"
)
qqline(dataa$casualty, col = "red")

qqnorm(
  dataa$property,
  ylim = c(0, 15000),
  xlim = c(0, 9),
  col = "blue",
  main = "QQ Plot - property"
)
qqline(dataa$property, col = "red")

```

```{r}
property = dataa$property
casualty = dataa$casualty

property_sorted = sort(property, decreasing = TRUE)
casualty_sorted = sort(casualty, decreasing = TRUE)

n_property = length(property_sorted)
n_casualty = length(casualty_sorted)

k3_property = ceiling(n_property^(2/3)/log(log(n_property)))
k3_casualty   = ceiling(n_casualty^(2/3)/log(log(n_casualty)))
u3_property = property_sorted[k3_property + 1]; u3_property
u3_casualty = casualty_sorted[k3_casualty + 1]; u3_casualty

par(mfrow=c(1,2))
mrl.plot(casualty, conf = 0.95, umin=0, umax=1000)
mrl.plot(property, conf = 0.95, umin=0, umax=10000)
u4_property = 4300
u4_casualty = 280

excess3_property = property[property > u3_property] - u3_property
excess3_casualty = casualty[casualty > u3_casualty] - u3_casualty
excess4_property = property[property > u4_property] - u4_property
excess4_casualty = casualty[casualty > u4_casualty] - u4_casualty
```

```{r}
fit_property = fpot(property, threshold = u3_property, model="gpd", std.err = FALSE)
xi_property = fit_property$estimate[["shape"]]
beta_property = fit_property$estimate[["scale"]]

fit_casualty = fpot(casualty, threshold = u3_casualty, model="gpd", std.err = FALSE)
xi_casualty = fit_casualty$estimate[["shape"]]
beta_casualty = fit_casualty$estimate[["scale"]]

ks_casualty = ks.test(excess3_casualty, "pgpd", xi_casualty, beta_casualty)
ks_property = ks.test(excess3_property, "pgpd", xi_property, beta_property)
```
```{r}
ecdf_data <- ecdf(excess3_property)

y <- seq(min(excess3_property), max(excess3_property), length.out = 1000)

gpd_cdf <- 1 - (1 + xi_property*y/beta_property)^(-1/xi_property)

par(
  pty = "s",
  mar = c(5,4,1,1)
)
plot(ecdf(excess3_property),
     xlim = c(0,110000),
     verticals = TRUE,
     do.points = FALSE,
     col = "blue",
     lwd = 2,
     xlab = "Y",
     ylab = "G(y)",
     main = "",
     las = 1)

lines(y,
      gpd_cdf,
      col = "red",
      lwd = 3)

box()

legend("bottomright",
       legend = c("Empirical CDF",
                  "Fitted GPD"),
       col = c("red", "blue"),
       lwd = 3)
```


```{r}
param = data.frame(
  Variabel = c("casualty", "property"),
  Xi       = c(xi_casualty, xi_property),
  Beta     = c(beta_casualty, beta_property)
)

print(param)

c2 = 60 #claim property
c1 = 10 #claim casualty
rho = 0.1 #loadingfactor
lambda = 3 #earthquake intensity
kx = 13 #extreme data
ky = 9
N = 54 #sample
```

```{r}
# Single risk CAT reinsurance premium casualty
V.casualty = ((lambda*c1*kx*param$Beta[1])/(N*(1-param$Xi[1])))+((rho*param$Beta[1]*c1*(sqrt(lambda*2*kx)))/(sqrt(N*(1-param$Xi[1])*(1-(2*param$Xi[1]))))); V.casualty
```
```{r}
# Single risk CAT reinsurance premium property
V.property = ((lambda*c2*ky*param$Beta[2])/(N*(1-param$Xi[2])))+((rho*param$Beta[2]*c2*(sqrt(lambda*2*ky)))/(sqrt(N*(1-param$Xi[2])*(1-(2*param$Xi[2]))))); V.property
```
```{r}
# Double risk CAT reinsurance premium
V.double = (lambda*(((c1*kx*param$Beta[1])/(N*(1-param$Xi[1])))+((c2*ky*param$Beta[2])/(N*(1-param$Xi[2])))))+(rho*(sqrt(lambda*((((c1^2)*kx*2*(param$Beta[1]^2))/(N*(1-param$Xi[1])*(1-2*param$Xi[1])))+(((c2^2)*ky*2*(param$Beta[2]^2))/(N*(1-param$Xi[2])*(1-2*param$Xi[2])))))))

V.double
```